// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: me8j5hgiwsuceYtrXTSFkj
// Component: KjHriqwzhHzL

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantszqoYg1BSzs5U } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZqoYG1bSZS5U/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: me8j5hgiwsuceYtrXTSFkj/projectcss
import sty from "./PlasmicPrivacyPolicy.module.css"; // plasmic-import: KjHriqwzhHzL/css

import lbLogoVfSlJptRmlfu from "./images/lbLogo.svg"; // plasmic-import: VfSlJPTRmlfu/picture

createPlasmicElementProxy;

export type PlasmicPrivacyPolicy__VariantMembers = {};
export type PlasmicPrivacyPolicy__VariantsArgs = {};
type VariantPropType = keyof PlasmicPrivacyPolicy__VariantsArgs;
export const PlasmicPrivacyPolicy__VariantProps = new Array<VariantPropType>();

export type PlasmicPrivacyPolicy__ArgsType = {};
type ArgPropType = keyof PlasmicPrivacyPolicy__ArgsType;
export const PlasmicPrivacyPolicy__ArgProps = new Array<ArgPropType>();

export type PlasmicPrivacyPolicy__OverridesType = {
  root?: Flex__<"div">;
  heroMessage?: Flex__<"div">;
  policy?: Flex__<"div">;
  footer?: Flex__<"div">;
};

export interface DefaultPrivacyPolicyProps {
  className?: string;
}

const $$ = {};

function PlasmicPrivacyPolicy__RenderFunc(props: {
  variants: PlasmicPrivacyPolicy__VariantsArgs;
  args: PlasmicPrivacyPolicy__ArgsType;
  overrides: PlasmicPrivacyPolicy__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszqoYg1BSzs5U()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link__n7DHm
            )}
            href={`/`}
            platform={"react"}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___2CpwK)}
              displayHeight={"50px"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "40%"
                  : "100%"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"305px"}
              loading={"lazy"}
              src={{
                src: lbLogoVfSlJptRmlfu,
                fullWidth: 305,
                fullHeight: 50,
                aspectRatio: 6.1
              }}
            />
          </PlasmicLink__>
          <Stack__
            as={"div"}
            data-plasmic-name={"heroMessage"}
            data-plasmic-override={overrides.heroMessage}
            hasGap={true}
            className={classNames(projectcss.all, sty.heroMessage)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lJjXf
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"Privacy Policy"}
                </span>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mDzb9
              )}
            >
              {"Last Updated: June 9, 2023"}
            </div>
          </Stack__>
          <div
            data-plasmic-name={"policy"}
            data-plasmic-override={overrides.policy}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.policy
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Introduction"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "LoanBlocks Inc. (\u201cLoanBlocks\u201d \u201cCompany,\u201d \u201cwe\u201d or \u201cus\u201d) is committed to protecting your privacy. The following policy (\u201cPrivacy Policy\u201d) describes our practices for collecting, using, maintaining, and disclosing information that we collect from you when you visit our website (our \u201cSite\u201d), the LoanBlocks Platform, or use any other products and services made available by us (collectively with the Site, the \u201cServices\u201d). We ask that you read this Privacy Policy carefully to understand our policies and practices regarding information and how we will treat it."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "This Privacy Policy may change from time to time. If we make any changes, we will post the changes on this page and indicate at the top of this page the date the policy was last revised. We will also notify you of any material changes either through a pop-up notice, email or through other reasonable means. Any such changes are effective immediately when we post them, and apply to all access to and use of the Services thereafter. Continued use of the Services after the date any such changes become effective constitutes acceptance of the new policy."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Terms not defined in this Privacy Policy have the same meaning as the Terms of Service, available at https://loanblocks.ai/terms."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Information We Collect and How We Collect Information"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "The information we collect about you depends on how you interact with us or use our Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"A. Information You Provide"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We may collect information you provide directly to the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Website User"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We collect certain information about you when you browse or otherwise use your public website to explore our Services or to learn more about us (\u201cWebsite User\u201d). For example, as a Website user, you may fill out a form or otherwise communicate with us. The types of personal information we may collect from you include name, email address, as well as company name and job title."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Authorized User"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We collect some or all of the following types of information directly from a business\u2019s employees, consultants, contractors, agents, and invitees who are authorized to access and use the Services under the rights granted to the business (\u201cAuthorized User\u201d). This includes when such users register for an Account with our Services, submit comments and other content, order products, or directly contact us with questions or feedback:"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Your name "}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Your telephone number "}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Your address"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Your email address"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Job title"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Your company name"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Your company address "}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Financial Information you provide "}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Business data "}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 We may also receive this information when administrators provide eligibility information to us to create Accounts for Authorized Users."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"B. Information We Automatically Collect"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We also collect certain information automatically when you visit or interact with the Services, including:"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Device and Usage Information: How you access our Services, including data about the device and network you use, your browser type and operating system, your Internet Protocol (IP) address, which is the number automatically assigned to the computer whenever you access the Internet and that can sometimes be used to derive general geographic area, other unique identifiers, including mobile device identification numbers, information about interactions with e-mail messages, such as the links clicked on and whether the messages were opened or forwarded. We also collect information about your activity on our Services, such as access times, links clicked, and the page you visited before navigating to our Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Geolocation information"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We collect the above information in a variety of ways, including by using \u201cSDKs,\u201d \u201cpixel tags,\u201d \u201cweb beacons,\u201d and \u201ccookies.\u201d"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Cookies are small bits of information that are stored by your computer\u2019s browser. You can decide if and how your computer will accept a cookie by configuring preferences or options in the browser. However, if you choose to reject cookies, you may not be able to use certain online products, services or features on the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Pixel tags are very small images or small pieces of data embedded in images, also known as \u201cweb beacons\u201d or \u201cclear GIFs,\u201d that can recognize cookies, the time and date a page is viewed, a description of the page where the pixel tag is placed, and similar information from a computer or device."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"How We Use Your Information"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We use information that we collect about you or that you provide to us to measure usage of the Services, to analyze the effectiveness of our Services, to conduct research, to improve, maintain, and enhance functionality of the Services, to provide support for the Services and respond to requests and inquiries, to provide you with notices, such as updates or changes that we may make to the Services, and to market and advertise the Services, including through targeted advertising on other platforms and promotional e-mail messages, directly or in partnership with other parties, to secure the Services and help protect the rights and property of LoanBlocks and others, and comply with our legal and financial obligations."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We may from time to time aggregate information in certain data analysis, reports, or other interpretations of trends for both internal and external purposes."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Choices About How We Collect, Use and Disclose Your Information"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We strive to provide you with choices regarding our collection, use and disclosure of the information you provide to us. The mechanisms listed below aim to provide you with control over such collection, use and disclosure:"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Marketing Communications. If you do not want us to send you marketing or promotional communications, you can opt-out by clicking the \u201cunsubscribe\u201d link in any such promotional emails, checking the relevant box located on the form on which we collect data or emailing us at eddie.garcia@loanblocks.ai."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Cookies. You have the option to accept or disable cookies at any time through your browser. You may refuse to accept browser cookies by activating the appropriate setting on their browser. If you choose to disable cookies, the user experience may be limited."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Third-Party Advertising. If you are interested in more information about tailored advertising and choices to prevent third parties from delivering tailored web advertisements, you may visit the following websites: http://www.networkadvertising.org/choices/ or http://www.aboutads.info/choices/. These opt-out tools are provided by third parties. We do not control or operate these tools or the choices that advertisers and others provide through these tools."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Disclosure of Your Information"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We want you to understand when and with whom we may share the information we collect. We may disclose information that we collect through the Services with third parties as follows:"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Service Providers. We may share your information with our agents and service providers that perform certain functions or services on our behalf, such as to host the Services, manage databases, host a store or other e-commerce platform, perform analyses, or conduct surveys."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Other Parties When Required By Law or as Necessary to Protect the Services. We may disclose your information to third parties in order to protect the legal rights, safety, and security of LoanBlocks and the users of our Services, the public, or others; enforce our Terms of Service; prevent fraud; and comply with or respond to law enforcement or a legal process or a request for cooperation by a government or other entity, whether or not legally required."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 In Connection With a Transfer of Assets. If we sell all or part of our business, make a sale or transfer of assets, are otherwise involved in a merger, financing, business transfer, or in the event of bankruptcy, or other certain corporate transactions, we may disclose your information in connection with, or during negotiations of such corporate transactions."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Other Parties With Your Consent. We may share information about you with other third parties when you consent to such sharing."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Aggregate Information. We may disclose to third parties information that does not describe or identify individual users, such as aggregate website usage data or demographic reports."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Links to Third-Party Sites and Services"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "The Services may contain links to other websites or online services that are operated and maintained by third parties and that are not under the control of or maintained by LoanBlocks. Such links do not constitute an endorsement by LoanBlocks of those other websites, the content displayed therein, or the persons or entities associated therewith. This Privacy Policy does not apply to this third-party content. We encourage you to review the privacy policies of these third- party websites or services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Do Not Track Signals"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Third parties may keep track of your browsing activities across third party websites. California Business & Professions Code Section 22575(b) provides that California residents are entitled to know whether we respond to \u201cDo Not Track\u201d browser signals. Certain web browsers enable users to activate a \u201cDo Not Track\u201d signal but we do not currently respond to the \u201cDo Not Track\u201d signal or other similar mechanisms."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Data Retention"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We strive to keep your information only as long as we need it for legitimate business purposes and as permitted by applicable legal requirements. If Users close their account, we will retain certain data for analytical purposes and recordkeeping integrity, as well as to prevent fraud, enforce our Terms of Service, take actions we deem necessary to protect the integrity of our Services or our users, or take other actions otherwise permitted by law. In addition, if certain information has already been provided to third parties as described in this Privacy Policy, retention of that information will be subject to those third parties\u2019 policies."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Accessing and Correcting Your Information"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "If you wish to access, update, or correct any personal information in our possession that you have previously submitted via the Services, you may log into your account and make updates. If you wish to make changes not available through their account settings, please contact us at eddie.garcia@loanblocks.ai."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Children Under the Age of 13"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Our Services are intended for individuals who are 13 years of age and older. If you are under the age of 13, you are not permitted to submit any personal information to us. If you believe we might have any information from or about a child under 13, please contact us at eddie.garcia@loanblocks.ai."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"International Users"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Please note that the Services are directed towards Website Users and Authorized Users who reside in the United States. By using the Services, you consent to the collection, storage, processing, and transfer of your information in and to the United States, or other countries and territories, pursuant to the laws of the United States. Some of these countries may not offer the same level of privacy protection as your own."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"Contact Information"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "If you have any questions about this Privacy Policy, please contact us at eddie.garcia@loanblocks.ai."
                }
              </span>
            </React.Fragment>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.column__pvGja)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wToYh
                )}
              >
                {"\u00a9 2024 LOANBLOCKS Inc. All rights reserved."}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column___5HUmo)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__haZMv
                )}
                href={`/terms`}
                platform={"react"}
              >
                {"Terms of Service"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.column__tiLu7)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__n6Qa
                )}
                href={`/privacy-policy`}
                platform={"react"}
              >
                {"Privacy Policy"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.column__miB12)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__aRWJ)}
                displayHeight={"32px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"189.935px"}
                loading={"lazy"}
                src={{
                  src: lbLogoVfSlJptRmlfu,
                  fullWidth: 305,
                  fullHeight: 50,
                  aspectRatio: 6.1
                }}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "heroMessage", "policy", "footer"],
  heroMessage: ["heroMessage"],
  policy: ["policy"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroMessage: "div";
  policy: "div";
  footer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPrivacyPolicy__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPrivacyPolicy__VariantsArgs;
    args?: PlasmicPrivacyPolicy__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPrivacyPolicy__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPrivacyPolicy__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPrivacyPolicy__ArgProps,
          internalVariantPropNames: PlasmicPrivacyPolicy__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPrivacyPolicy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPrivacyPolicy";
  } else {
    func.displayName = `PlasmicPrivacyPolicy.${nodeName}`;
  }
  return func;
}

export const PlasmicPrivacyPolicy = Object.assign(
  // Top-level PlasmicPrivacyPolicy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroMessage: makeNodeComponent("heroMessage"),
    policy: makeNodeComponent("policy"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicPrivacyPolicy
    internalVariantProps: PlasmicPrivacyPolicy__VariantProps,
    internalArgProps: PlasmicPrivacyPolicy__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Loanblocks | Privacy Policy",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPrivacyPolicy;
/* prettier-ignore-end */
