// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: me8j5hgiwsuceYtrXTSFkj
// Component: PcdRufHrje6g

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: T868m2MaLz1c/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantszqoYg1BSzs5U } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZqoYG1bSZS5U/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: me8j5hgiwsuceYtrXTSFkj/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: PcdRufHrje6g/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: aO9uawZq_T88/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: -teSAeVyFMKP/icon
import image8NXzyd5EFcuIv from "./images/image8.png"; // plasmic-import: NXzyd5eFcuIV/picture
import logo031Svg296FOkvJdFd from "./images/logo031Svg2.svg"; // plasmic-import: _96_FOkvJdFd/picture
import logo031SvgCnJ8Hcq729Cq from "./images/logo031Svg.svg"; // plasmic-import: CnJ8hcq729CQ/picture
import image57NTfM34LiwI from "./images/image5.svg"; // plasmic-import: 7NTfM34liwI_/picture
import image4CxaQw4HiAgA from "./images/image4.png"; // plasmic-import: cxa-QW4HiAgA/picture
import image6MNc1IoMrfi1G from "./images/image6.svg"; // plasmic-import: mNc1IoMrfi1G/picture
import image7RvAoxMxX1Ufo from "./images/image7.svg"; // plasmic-import: RvAOXMxX1ufo/picture
import screenshot20240806At85828PMpngHZFj9Bkn1Xz from "./images/screenshot20240806At85828PMpng.png"; // plasmic-import: -hZFj9Bkn1xz/picture
import image9064XjGfWkuk from "./images/image9.svg"; // plasmic-import: 064xjGfWKUK_/picture
import image10JvnVng7SwSl2 from "./images/image10.png"; // plasmic-import: jvnVng7SWSl2/picture
import image11TNqNfWqmSAmN from "./images/image11.png"; // plasmic-import: tNqNfWqmSAmN/picture

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  verticalLayout?: Flex__<"div">;
  circle?: Flex__<"div">;
  topRightDesignPosition?: Flex__<"div">;
  topRightDesign?: Flex__<"div">;
  heroMessage?: Flex__<"div">;
  builtBy?: Flex__<"div">;
  logos?: Flex__<"div">;
  useCases?: Flex__<"div">;
  section?: Flex__<"section">;
  offices?: Flex__<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const $$ = {};

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszqoYg1BSzs5U()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"verticalLayout"}
            data-plasmic-override={overrides.verticalLayout}
            className={classNames(projectcss.all, sty.verticalLayout)}
          >
            <div
              data-plasmic-name={"circle"}
              data-plasmic-override={overrides.circle}
              className={classNames(projectcss.all, sty.circle)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__v5Tj)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "135px"
                    : "451px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "202px"
                    : "235px"
                }
                loading={"lazy"}
                src={{
                  src: image8NXzyd5EFcuIv,
                  fullWidth: 988,
                  fullHeight: 1372,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"topRightDesignPosition"}
              data-plasmic-override={overrides.topRightDesignPosition}
              className={classNames(projectcss.all, sty.topRightDesignPosition)}
            >
              <div
                data-plasmic-name={"topRightDesign"}
                data-plasmic-override={overrides.topRightDesign}
                className={classNames(projectcss.all, sty.topRightDesign)}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__rSHbz)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ffgPt
                    )}
                  >
                    {"Join Waitlist"}
                  </div>
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button___9X9UT)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zHp2I
                    )}
                  >
                    {"Join Waitlist"}
                  </div>
                </Button>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jweV)}
                  displayHeight={"50px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "16.43%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "305px"
                  }
                  loading={"lazy"}
                  src={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? {
                          src: logo031SvgCnJ8Hcq729Cq,
                          fullWidth: 186,
                          fullHeight: 22,
                          aspectRatio: 8.454545
                        }
                      : {
                          src: logo031Svg296FOkvJdFd,
                          fullWidth: 186,
                          fullHeight: 22,
                          aspectRatio: 8.454545
                        }
                  }
                />

                <Button
                  className={classNames("__wab_instance", sty.button__aDxCo)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mer6S
                    )}
                  >
                    {"Join Waitlist"}
                  </div>
                </Button>
              </div>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__q7Tc)}
              displayHeight={"50px"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "16.43%"
                  : "100%"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "100%"
                  : "305px"
              }
              loading={"lazy"}
              src={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? {
                      src: logo031SvgCnJ8Hcq729Cq,
                      fullWidth: 186,
                      fullHeight: 22,
                      aspectRatio: 8.454545
                    }
                  : {
                      src: logo031Svg296FOkvJdFd,
                      fullWidth: 186,
                      fullHeight: 22,
                      aspectRatio: 8.454545
                    }
              }
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"heroMessage"}
              data-plasmic-override={overrides.heroMessage}
              hasGap={true}
              className={classNames(projectcss.all, sty.heroMessage)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__l4Fdg)}>
                <div className={classNames(projectcss.all, sty.freeBox__so1Iz)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__skG8R)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lMw4F
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {"Boost corporate loan deal success"}
                          </span>
                        </React.Fragment>
                      ) : (
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {"Boost corporate loan deal success"}
                          </span>
                        </React.Fragment>
                      )}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__uNEmu)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kBFgS
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {"Win deals "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"faster"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {
                              " - accelerate contract review and reduce manual work with AI."
                            }
                          </span>
                        </React.Fragment>
                      ) : (
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {"Win deals "}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"faster"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {
                              " - accelerate contract review and reduce manual work with AI."
                            }
                          </span>
                        </React.Fragment>
                      )}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bkFsB)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___1C4Ib
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__t326
                        )}
                      >
                        {"Join Waitlist"}
                      </div>
                    </Button>
                  </div>
                </div>
              </div>
            </Stack__>
            <div
              data-plasmic-name={"builtBy"}
              data-plasmic-override={overrides.builtBy}
              className={classNames(projectcss.all, sty.builtBy)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oto8Z
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  "Arrangers are structuring more complex loans, hindering efficient administrative work."
                ) : (
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {
                        "Arrangers are structuring more complex loans, hindering efficient administrative work."
                      }
                    </span>
                  </React.Fragment>
                )}
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"logos"}
                data-plasmic-override={overrides.logos}
                hasGap={true}
                className={classNames(projectcss.all, sty.logos)}
              >
                <div className={classNames(projectcss.all, sty.column__ie4AU)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iwau1)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___96Fg9
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__xseQs)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "11px"
                            : "40px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "auto"
                            : "100%"
                        }
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: image57NTfM34LiwI,
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: 1
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qUkDw)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "13px"
                            : "auto"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "auto"
                            : "100%"
                        }
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "13px"
                            : "64px"
                        }
                        loading={"lazy"}
                        src={{
                          src: image4CxaQw4HiAgA,
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cUl3E
                    )}
                  >
                    {"Workforce"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eyIIe
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "\nAdding more headcount?\n\nEnable your employees to be more productive."
                      : "Adding more headcount?\n\nEnable your employees to be more productive."}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__u93IO
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Learn more"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.column__tHjCl)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ligM2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rmgIt)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__rfT43)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "11px"
                            : "40px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "auto"
                            : "100%"
                        }
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: image6MNc1IoMrfi1G,
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: 1
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ohV3T)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "13px"
                            : "auto"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: image4CxaQw4HiAgA,
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__guRjb
                    )}
                  >
                    {"Operations"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qFjfX
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "\nHiring offshore talent? \n\nMaintain onshore employees and quality control."
                      : "Hiring offshore talent?\n\nMaintain onshore employees and save on quality control."}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__q6ZUn
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Learn more"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.column___7NJaP)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___3Wha)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bJsVp)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__le1Up)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "11px"
                            : "40px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: image7RvAoxMxX1Ufo,
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: 1
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__jpAdC)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "13px"
                            : "auto"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: image4CxaQw4HiAgA,
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__arvj5
                    )}
                  >
                    {"Compliance"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wxNtK
                    )}
                  >
                    {
                      "Legacy software?\n\nIntegrate compliant AI to enhance existing systems. "
                    }
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___8UkyA
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Learn more"}
                  </PlasmicLink__>
                </div>
              </Stack__>
            </div>
            <div
              data-plasmic-name={"useCases"}
              data-plasmic-override={overrides.useCases}
              className={classNames(projectcss.all, sty.useCases)}
            >
              <section
                data-plasmic-name={"section"}
                data-plasmic-override={overrides.section}
                className={classNames(projectcss.all, sty.section)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eOlwd
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000", fontWeight: 600 }}
                      >
                        {"We "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#40AA71", fontWeight: 600 }}
                      >
                        {"simplify credit agreements"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000", fontWeight: 600 }}
                      >
                        {" for finance teams"}
                      </span>
                    </React.Fragment>
                  ) : (
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#343434" }}
                      >
                        {"We "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#40AA71" }}
                      >
                        {"simplify"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#343434" }}
                      >
                        {" "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#40AA71" }}
                      >
                        {"legal"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#343434" }}
                      >
                        {" "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#40AA71" }}
                      >
                        {"agreements"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#343434" }}
                      >
                        {" for finance teams"}
                      </span>
                    </React.Fragment>
                  )}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ymPwN
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Analyze complex credit "}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#212121" }}
                    >
                      {"documents"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {" faster, cheaper, and improve accuracy."}
                    </span>
                  </React.Fragment>
                </div>
              </section>
              <Stack__
                as={"div"}
                data-plasmic-name={"offices"}
                data-plasmic-override={overrides.offices}
                hasGap={true}
                className={classNames(projectcss.all, sty.offices)}
              >
                <div className={classNames(projectcss.all, sty.column___6Hz3A)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sotjp
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000" }}
                      >
                        {"Drive deal success"}
                      </span>
                    </React.Fragment>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__yX3Qo)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "148px"
                        : "526px"
                    }
                    loading={"lazy"}
                    src={{
                      src: screenshot20240806At85828PMpngHZFj9Bkn1Xz,
                      fullWidth: 1134,
                      fullHeight: 784,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mjoS3
                    )}
                  >
                    {
                      "Finance professionals, streamline legal contract processing with our AI."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__mjGNx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__u0IVk
                      )}
                    >
                      {"Join Waitlist"}
                    </div>
                  </Button>
                </div>
                <div className={classNames(projectcss.all, sty.column___3CYdv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rkYhn
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000" }}
                      >
                        {" Why is LB"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700, color: "#000000" }}
                      >
                        {" "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700, color: "#40AA71" }}
                      >
                        {"powerful"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000" }}
                      >
                        {"?"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2L5Tk
                    )}
                  >
                    {
                      "Win deals faster by leveraging LLMs, Corporate Credit, & Legal professionals."
                    }
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__yIzwF)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___94Sxk)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hZIt)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "57px"
                            : "218px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "113px"
                            : "370px"
                        }
                        loading={"lazy"}
                        src={{
                          src: image9064XjGfWkuk,
                          fullWidth: 380,
                          fullHeight: 215,
                          aspectRatio: 1.767442
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hYiWz)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__k2NyK)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "57px"
                            : "218px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "105px"
                            : "370px"
                        }
                        loading={"lazy"}
                        src={{
                          src: image10JvnVng7SwSl2,
                          fullWidth: 760,
                          fullHeight: 430,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qsXbf)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___7Jd5Z)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "57px"
                            : "218px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "101px"
                            : "370px"
                        }
                        loading={"lazy"}
                        src={{
                          src: image11TNqNfWqmSAmN,
                          fullWidth: 760,
                          fullHeight: 433,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__l99S4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eXulU
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"Close deals faster, from months to weeks. "}
                          </span>
                          <React.Fragment>
                            {
                              "\n\n\nAI tools to process large documents quickly."
                            }
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xh8T
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"Close deals faster, from months to weeks."}
                          </span>
                          <React.Fragment>
                            {"\n\nAI tools to process large documents quickly."}
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hFYvd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iknyw
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {
                              "Reduce operational costs and boost productivity.        "
                            }
                          </span>
                          <React.Fragment>
                            {
                              "\n\nStreamline routine tasks and reduce manual effort."
                            }
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5W7Mk
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"Reduce operational costs and boost productivity."}
                          </span>
                          <React.Fragment>
                            {
                              "\n\nStreamline routine tasks and reduce manual effort."
                            }
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___4X8Ku)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xmJ0
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {
                              "Focus on high-value while AI handles repetitive tasks"
                            }
                          </span>
                          <React.Fragment>
                            {
                              "\n\n\nAI systems that validate contract details efficiently."
                            }
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nnMcw
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {
                              "Focus on high-value while AI handles repetitive tasks"
                            }
                          </span>
                          <React.Fragment>
                            {
                              "\n\nCross-validating AI system to ensure accuracy."
                            }
                          </React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__d8Uac)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__n8ICt)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__dmyI)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__sm9KY)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "20px"
                            : "50px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "95.45%"
                            : "100%"
                        }
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "68px"
                            : "299px"
                        }
                        loading={"lazy"}
                        src={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? {
                                src: logo031SvgCnJ8Hcq729Cq,
                                fullWidth: 186,
                                fullHeight: 22,
                                aspectRatio: 8.454545
                              }
                            : {
                                src: logo031Svg296FOkvJdFd,
                                fullWidth: 186,
                                fullHeight: 22,
                                aspectRatio: 8.454545
                              }
                        }
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wFqap
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "\nLOANBLOCKS INC.\n14 Wall Street, Suite 2028\nNew York\nNY 10005\nUSA"
                          : "\nLOANBLOCKS INC.\n14 Wall Street, Suite #2028\nNew York\nNY 10005\nUSA"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ssjBv)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__rtznp
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Company"
                          : "Company"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__xuq1L
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "About Us"
                          : "About Us"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___7HIob
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Mission"
                          : "Mission"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__uV9U0
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Testimonials"
                          : "Testimonials"}
                      </PlasmicLink__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___9VTsk)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__hKKq4
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Our Works"
                          : "Our Works"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__gHrDy
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Pricing"
                          : "Customer"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__tNmFj
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Customer"
                          : "Product"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__xjgts
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Product"
                          : "Pricing"}
                      </PlasmicLink__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__my2I6)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___9NlH
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {"Support"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__exHg
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {"FAQ"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__wLowM
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {"Privacy Policy"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___754A
                        )}
                        href={"https://www.plasmic.app/"}
                        platform={"react"}
                      >
                        {"Terms of Service"}
                      </PlasmicLink__>
                    </div>
                  </Stack__>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__yY1Na
            )}
          >
            {hasVariant(globalVariants, "screen", "mobileOnly")
              ? "\n\n\n\n\n\n\n\n\u00a92024 LOANBLOCKS INC. All Right Reserved"
              : "\n\u00a92024 LOANBLOCKS INC. All right reserved"}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "verticalLayout",
    "circle",
    "topRightDesignPosition",
    "topRightDesign",
    "heroMessage",
    "builtBy",
    "logos",
    "useCases",
    "section",
    "offices"
  ],
  verticalLayout: [
    "verticalLayout",
    "circle",
    "topRightDesignPosition",
    "topRightDesign",
    "heroMessage",
    "builtBy",
    "logos",
    "useCases",
    "section",
    "offices"
  ],
  circle: ["circle"],
  topRightDesignPosition: ["topRightDesignPosition", "topRightDesign"],
  topRightDesign: ["topRightDesign"],
  heroMessage: ["heroMessage"],
  builtBy: ["builtBy", "logos"],
  logos: ["logos"],
  useCases: ["useCases", "section", "offices"],
  section: ["section"],
  offices: ["offices"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  verticalLayout: "div";
  circle: "div";
  topRightDesignPosition: "div";
  topRightDesign: "div";
  heroMessage: "div";
  builtBy: "div";
  logos: "div";
  useCases: "div";
  section: "section";
  offices: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    verticalLayout: makeNodeComponent("verticalLayout"),
    circle: makeNodeComponent("circle"),
    topRightDesignPosition: makeNodeComponent("topRightDesignPosition"),
    topRightDesign: makeNodeComponent("topRightDesign"),
    heroMessage: makeNodeComponent("heroMessage"),
    builtBy: makeNodeComponent("builtBy"),
    logos: makeNodeComponent("logos"),
    useCases: makeNodeComponent("useCases"),
    section: makeNodeComponent("section"),
    offices: makeNodeComponent("offices"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Loanblocks | Accelerate Corporate Credit Operations",
      description:
        "Loanblocks transforms data into decisions in corporate credit operations, including CLO structuring, fund formation, monthly reporting, and more.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
