// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: me8j5hgiwsuceYtrXTSFkj
// Component: ZLAmOnoU8Njv

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantszqoYg1BSzs5U } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZqoYG1bSZS5U/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: me8j5hgiwsuceYtrXTSFkj/projectcss
import sty from "./PlasmicTermsOfService.module.css"; // plasmic-import: ZLAmOnoU8Njv/css

import lbLogoVfSlJptRmlfu from "./images/lbLogo.svg"; // plasmic-import: VfSlJPTRmlfu/picture

createPlasmicElementProxy;

export type PlasmicTermsOfService__VariantMembers = {};
export type PlasmicTermsOfService__VariantsArgs = {};
type VariantPropType = keyof PlasmicTermsOfService__VariantsArgs;
export const PlasmicTermsOfService__VariantProps = new Array<VariantPropType>();

export type PlasmicTermsOfService__ArgsType = {};
type ArgPropType = keyof PlasmicTermsOfService__ArgsType;
export const PlasmicTermsOfService__ArgProps = new Array<ArgPropType>();

export type PlasmicTermsOfService__OverridesType = {
  root?: Flex__<"div">;
  heroMessage?: Flex__<"div">;
  terms?: Flex__<"div">;
  footer?: Flex__<"div">;
};

export interface DefaultTermsOfServiceProps {
  className?: string;
}

const $$ = {};

function PlasmicTermsOfService__RenderFunc(props: {
  variants: PlasmicTermsOfService__VariantsArgs;
  args: PlasmicTermsOfService__ArgsType;
  overrides: PlasmicTermsOfService__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszqoYg1BSzs5U()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link__r38W6
            )}
            href={`/https/www.loanblocks.ai`}
            platform={"react"}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__vjVgG)}
              displayHeight={"50px"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "40%"
                  : "100%"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"305px"}
              loading={"lazy"}
              src={{
                src: lbLogoVfSlJptRmlfu,
                fullWidth: 305,
                fullHeight: 50,
                aspectRatio: 6.1
              }}
            />
          </PlasmicLink__>
          <Stack__
            as={"div"}
            data-plasmic-name={"heroMessage"}
            data-plasmic-override={overrides.heroMessage}
            hasGap={true}
            className={classNames(projectcss.all, sty.heroMessage)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yyjfw
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"Terms of Service"}
                </span>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__g7Vm
              )}
            >
              {"Last Updated: June 9, 2023"}
            </div>
          </Stack__>
          <div
            data-plasmic-name={"terms"}
            data-plasmic-override={overrides.terms}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.terms
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"1. Acceptance of the Terms "}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Welcome to LoanBlocks. Please read on to learn the rules, restrictions and other terms of service, (these \u201cTerms\u201d) governing your use of the LoanBlocks platform and services (the \u201cPlatform\u201d) as well as LoanBlocks' website (the \u201cSite\u201d and, together with the Platform, the \u201cServices\u201d) made available by\u00a0LoanBlocks Inc.\u00a0(\u201cLoanBlocks,\u201d\u00a0\u201cCompany,\u201d \u201cwe,\u201d  \u201cus\u201d\u00a0or\u00a0\u201cour\u201d). Please read these Terms carefully. By accessing, viewing or otherwise using the Services or by clicking to accept or agree to the Terms when this option is made available to you, you (1) acknowledge that you have read and understood these Terms, (2) represent and warrant  that you meet all of our eligibility requirements for using the Services  as described in these Terms, and (3) accept and agree to be bound  by these Terms, including any other terms applicable to the Services that are incorporated herein by reference. These Terms apply to you in whatever capacity you access and use the Services\u00a0\u2013\u00a0whether you are accessing the Services on behalf of your organization, have been invited to access the Services by a client of ours, or otherwise. If you are using the Services on behalf of your organization, you are agreeing to these Terms for that entity and are representing to us that you have the authority to bind that entity to these Terms (in which case\u00a0\u201cyou\u201d\u00a0will refer to that entity). If your organization has agreed to additional terms of service or use with respect to the Services, such as a Master Services Agreement, as defined below, all of those terms are incorporated into these Terms, as well as any additional terms and conditions made available by us through the Services. If you do not accept these Terms or do not satisfy the eligibility requirements set forth below, you may not access or use the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "THESE TERMS CONTAINS A MANDATORY ARBITRATION PROVISION THAT, AS FURTHER SET FORTH BELOW, REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR ANY OTHER COURT PROCEEDINGS, OR CLASS ACTIONS OF ANY KIND."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"2. Privacy Policy"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Your use of, and participation in, the Services offered by the Company is subject to the terms set forth in our privacy policy located at https://loanblocks.ai/privacy-policy\u00a0(the\u00a0\u201cPrivacy Policy\u201d). Our Privacy Policy details how we collect and use your information."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"3. Changes to the Terms of Service"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We reserve the right to update and revise these Terms at any time by notifying you of such changes by any reasonable means, including by posting the revised Terms through the Site. We\u2019ll make sure to also change the \u201cLast Updated\u201d date at the top of this page so you can tell if these Terms have changed since your last visit. Any such changes are effective immediately when we post them and apply to all access to and use of the Services thereafter. Please review these Terms regularly because once we post any changes, your continued use of the Services constitutes your acceptance of the revised Terms."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"4. Access to Services; Account Registration"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "To access our Services made available through the Platform, you will be required to register with the Platform and create a user account (an \u201cAccount\u201d). To access certain member only Services available through the Site, you may also be required to go through a separate onboarding process and create a member Account. If you create an Account, you are solely responsible for any activity that occurs through your Account. In order for us to provide you the best possible Service, you agree to provide us with complete, accurate, and updated information for your Account at all times. You agree that all information that you submit upon creation of your Account is accurate and truthful. If any information is incorrect or outdated, it can lead to errors or delays, for which we will not be responsible."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You should not share your Account information. You should not use another person\u2019s Account or registration information for the Services without permission. Similarly, no one else should be able to use your Account without permission. You are solely responsible for keeping your Account and Account password secure and for any consequence resulting from your failure to do so. You should never publish, distribute, or post login information for your Account."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We have the right to disable any username, password or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms. You can always delete your Account by emailing us at eddie.garcia@loanblocks.ai."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "By accessing the Services, you warrant that: 1. (i) You are legally capable of entering into binding contracts; 2. (ii) All Account registration information you submit is truthful and accurate; 3. (ii) All Account registration information you submit is truthful and accurate; 4. (iv) Your use of the Services does not violate any applicable law or regulation. Finally, if your access of the Services involves or related to (a) the creation or distribution of any information relating to the offer or sale of securities of any entity or (b) any other activities or conduct arising out of, incident to or connected in any way with the offer or sale of securities of any entity (\u201cSecurities-Related Activities\u201d), you warrant that you have all necessary licenses and registrations under applicable laws, regulations and the rules of any applicable self-regulatory organization to conduct such Securities-Related Activities."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"5. Payment"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Payment terms for customers using our paid Services can be found in the Master Services Agreement entered into by you (or your organization) and us (the \u201cMaster Services Agreement\u201d)."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"6. Changing Fees and Charges"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We may at any time and from time to time, in our sole discretion (but subject to the terms of the Master Services Agreement (as applicable)), change the fees and charges, or add new fees and charges, in relation to any of the Services. We may also at any time and from time to time, in our sole discretion (but subject to the terms of the Master Services Agreement (as applicable)), change or remove any of the pricing models in place."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"7. Account Terminations and Suspensions"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "A user may stop using the Services and terminate their Account if they wish to do so subject to these Terms and any other agreements with LoanBlocks (such as the Master Services Agreement). Please contact eddie.garcia@loanblocks.ai for further information. These Terms are effective until terminated. We may terminate (or suspend access to) your use of the Services or your Account, for any reason in our discretion, including your breach of these Terms. LoanBlocks has the sole right to decide (but will acting reasonably in doing so) whether you are in violation of any of the restrictions set forth in these Terms. Upon any such termination or suspension, your right to use the Services immediately cease, and we may, without liability to you or any third party, immediately deactivate or delete your user name, password and Account, and all associated materials, without any obligation to provide any further access to such materials."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Account termination may result in destruction of any Content associated with your Account, so keep that in mind before you decide to terminate your Account. We will try to provide advance notice to you prior to our terminating your Account so that you are able to retrieve any important User Submissions you may have stored in your Account (to the extent allowed by law and these Terms), but we may not do so if we determine it would be impractical, illegal, not in the interest of someone\u2019s safety or security, or otherwise harmful to the rights or property of LoanBlocks. Sections 1, 2, 4 - 13, 15 - 20 survive any termination or expiration of these Terms."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"8. Eligibility; User Restrictions"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We only permit individuals who are at least 18 years old, or the age of majority in your province, territory or country, and who can form legally binding contracts with us to use the Services. BY USING THE SERVICES, YOU AFFIRM THAT YOU ARE OF LEGAL AGE TO ENTER INTO THESE TERMS."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "The Services are controlled or operated (or both) from the United States, and is not intended to subject Company to any non-U.S. jurisdiction or law. You can only use or receive the Services to the extent the laws of your jurisdiction or the United States do not bar you from doing so. Please make sure these Terms are in compliance with all laws, rules and regulations that apply to you. Any use of the Services is at your own risk, you are solely responsible for ensuring compliance with all applicable laws, rules and regulations of your specific jurisdiction."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"9. Use of the Services; Restrictions on Use"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We may from time to time in our sole discretion (but subject to the terms of the Master Services Agreement) develop and provide updates to the Services, change the Services, restrict access to the Services (including to registered users) or withdraw or terminate the Services entirely, and, subject to the terms of the Master Services Agreement, we reserve the right to do so in our sole discretion without notice. Any such updates or changes will be deemed part of the Services and subject to all terms and conditions of these Terms. We will not be liable to you or any third party for any modification, suspension or discontinuance of the Services. In the event of modification or termination, you will still be bound by your obligations under these Terms, including but not limited to the warranties made by you, and by the disclaimers and limitations of liability, and other surviving obligations as specified in Section 7."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You may only use the Services as explicitly authorized and in compliance with any policies made available to you within the Services, including as specified in an applicable Master Services Agreement. You may not use such proprietary information or materials in any way whatsoever except for permitted use of the Services. No portion of the Services may be reproduced in any form or by any means. Without limiting the foregoing, you may not do any of the following while accessing or using the Services:"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Express or imply that any statements you make are endorsed by LoanBlocks;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Scrape the Services or any information contained therein, or use other automated or manual means to take any Content hosted on the Services without our express prior written consent;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Post, transmit or otherwise make available through or in connection with the Services any virus, worm, Trojan horse, Easter egg, time bomb, spyware or other computer code, file or program that is or is potentially harmful or invasive or intended to damage or hijack the operation of, or to monitor the use of, any hardware, software or equipment (each, a \u201cVirus\u201d);"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Modify, adapt, translate, reverse engineer, decompile, decode, adapt. disassemble or convert into human readable form any of the Contents of the Services not intended to be so read;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Take any action that imposes or may impose (as determined by us in our sole discretion) an unreasonable or disproportionately large load on our or our third-party providers\u2019 infrastructure;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Interfere or attempt to interfere with the proper working of the Services or any activities conducted on the Services;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Bypass, circumvent, or attempt to bypass or circumvent any measures we may use to prevent or restrict access to the Services, including without limitation other Accounts, computer systems, security or networks connected to the Services;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Run any form of auto-responder or \u201cspam\u201d on the Services;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"\u2022 Render any part of the Services unusable;"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Access or use the Services for any illegal or unauthorized purpose, including any applicable sanctions or export control laws;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 In any manner that is (1) harmful, threatening, harassing, degrading, hateful, intimidating or otherwise fails to respect the rights and dignity of others; (2) defamatory, libelous, fraudulent or otherwise tortious; (3) obscene, indecent, pornographic or otherwise objectionable;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Frame or mirror any portion of the Services, or otherwise incorporate any portion of the Services into any product or service, without our express prior written consent;"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Infringe or violate the intellectual property rights or any other rights of any other person (including LoanBlocks); or"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "\u2022 Otherwise take any action in violation of these Terms."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You are responsible for obtaining, maintaining and paying for all hardware and all telecommunications and other services needed to use the Services. Without limiting any of the 5 foregoing, you represent and warrant that, to the extent your use of the Services involves Securities-Related Activities: (1) such information will be not contain any untrue or misleading statement of a material fact and will not omit to state a material fact necessary in order to make the statements made in such information, in light of the circumstances under which they were made, not misleading; (2) you will not employ, in connection with the Services, any device, scheme or artifice to defraud, and you will not engage, in connection with the Services, in any act, practice or course of business that operates or would operate as a fraud or deceit upon any person; and (3) you will use the Services in a manner that is not intended to, and could not reasonably be expected to, violate, breach or fail to comply with any United States federal or state law applicable to the offer or sale of securities."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"10. Links to Third Party Services"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We may provide links to third party services or websites for you to access (\u201cThird Party Links\u201d). You acknowledge that any access is at your sole discretion and for your information only. We do not review or endorse any of those services or websites. We are not responsible in any way for: (a) the availability of, (b) the privacy practices of, (c) the content, advertising, products, goods or other materials or resources on or available from, or (d) the use to which others make of these other websites and services. We are also not responsible for any damage, loss or offense caused or alleged to be caused by, or in connection with, the use of or reliance on such websites or services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"11. Intellectual Property"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Except as otherwise expressly granted to you in these Terms, we and our licensors own and retain all right, title and interest in the Services, including without limitation, all technology and processes, enhancements or modifications thereto, trademarks, service marks, site design, text, video, graphics, logos, images and icons, as well as the arrangement thereof. You acknowledge that the Services contain proprietary content, information and material protected by applicable intellectual property and other laws, including but not limited to copyright and trademark laws, and you agree that, except with our prior written consent or as explicitly provided in these Terms, using the Services does not (1) give you any ownership of any intellectual property rights in our Services or (2) grant you the right to display, modify, reproduce, distribute, create derivative works of, download, store, transmit or otherwise use any of our intellectual property. Any unauthorized use of any Content or materials on the Services is strictly prohibited and violates copyright, trademark, and/or other intellectual property laws, and/or the laws of privacy, publicity, and/or communications regulations and statutes."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "All Content not explicitly indicated as downloadable may not be downloaded or copied from the Services. You may not otherwise download, display, copy, reproduce, distribute, modify, perform, transfer, create derivative works from, sell or otherwise exploit any Content, code, data or materials in the Services. If you make other use of the Services, or the Content, code, data or materials thereon, except as otherwise provided, you may violate copyright and other laws of the United States, other countries, as well as applicable state laws and may be subject to liability for such unauthorized use."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"12. User Generated Content and User Submissions"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Anything you post, upload, share, store, or otherwise provide through the Services, in whatever format, is a \u201cUser Submission.\u201d Some User Submissions may be viewable or accessible by other users. In order to display your User Submissions on the Services, and to allow other users to view or access them (where applicable), you grant us certain rights in those User Submissions. Please note that all of the following licenses are subject to our Privacy Policy to the extent they relate to User Submissions that are also your personally identifiable information."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "For all User Submissions, you hereby grant LoanBlocks a license to translate, modify (for technical purposes) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services, as described in more detail below. This is a license only \u2013 your ownership in User Submissions is not affected."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "If you share a User Submission only in a manner that limits access and viewing to certain specified users (for example, a private message to one or more other users) (a \u201cLimited Audience User Submission\u201d), then you grant LoanBlocks the licenses above, as well as a license to display, perform, and distribute your Limited Audience User Submission for the sole purpose of making that Limited Audience User Submission accessible to such other specified users, and providing the Services necessary to do so. Also, you grant such other specified users a license to access that Limited Audience User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "If you (1) share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view, or (2) provide us with any feedback, suggestions, improvements, enhancements, and/or feature requests relating to the Services (\u201cFeedback\u201d) (each of the foregoing, a \u201cPublic User Submission\u201d), then you grant LoanBlocks the licenses above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of making that Public User Submission accessible to all LoanBlocks users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with the Services and/or otherwise in connection with Company\u2019s business, which may include licensing to third parties. Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services and in accordance with these Terms. You also hereby acknowledge and agree that Feedback is not confidential, and that your provision of such Feedback is gratuitous, unsolicited and without restriction, and does not place us under any fiduciary or other obligation."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You agree that the licenses you grant are royalty-free, non-exclusive, perpetual, fully sublicensable (through multiple tiers), irrevocable, transferrable, and worldwide, provided that when you delete your Account, we will stop displaying your User Submissions (other than Public User Submissions and Limited Audience User Submissions, which may remain fully available) to other users (if applicable), but you understand and agree that it may not be possible to completely delete that Content from LoanBlocks\u2019 records, and that your User Submissions may remain accessible or viewable elsewhere to the extent that they were copied or stored by other users of the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Finally, you understand and agree that LoanBlocks, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Any information or Content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such Content originated, and you access all such information and Content at your own risk, and we aren\u2019t liable for any errors or omissions in that information or Content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can\u2019t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You understand and agree that your identity may be discovered by other users on the Services. You provide User Submissions at your own risk, and you understand that LoanBlocks\u2019 privacy obligations are as set forth in the Privacy Policy. If you do not accept this risk, do not use the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You are responsible for all User Submissions you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You also represent and warrant that all of your User Submissions are complete and accurate, and are not fraudulent, tortious or otherwise in violation of any applicable law or any right of any third party. You further irrevocably waive any \u201cmoral rights\u201d or other rights with respect to attribution of authorship or integrity of materials regarding any User Submissions that you may have under any applicable law under any legal theory. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services. You are solely responsible for ensuring that your provision of any personal data to the Services complies with applicable data protection laws."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We may (but have no obligation to) monitor, evaluate, alter or remove User Submissions before or after they appear on the Services, or analyze your access to or use of the Service. We may disclose information regarding your access to and use of the Services, and the circumstances surrounding such access and use, to anyone for any reason or purpose."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Your interactions with organizations and/or individuals found on or through the Services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that LoanBlocks shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  'If there is a dispute between users on the Services, or between users and any third party, you agree that LoanBlocks is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release LoanBlocks, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which, if known by him or her must have materially affected his or her settlement with the debtor.\u201d'
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"13. Confidentiality"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Certain information you may access on the Services, including User Submissions you make or view, may be confidential in nature. As such, it is understood and agreed that you should treat all information that you view while using the Services or the Platform as confidential, and not to be downloaded and distributed to any third parties outside of the Platform, unless explicit consent is granted by the user submitting the User Submission in question."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Nothing herein shall limit or impair your right to disclose information, if legally required to do so, in any judicial, administrative or governmental proceeding, subject to your prior notification of the relevant owner of the information."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Your obligations of confidentiality and non-disclosure may also be set forth in more detail in a separate agreement and nothing in this Platform will be deemed to supersede or modify your obligations under that agreement. If you do not believe you are bound by such a non-disclosure agreement, you must exit the Platform now."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"14. Availability of the Services"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Although we aim to offer you the best service possible, we make no promise that the Services will meet your requirements and we cannot guarantee that the Services will be fault free, correct, complete or secure or that access will be uninterrupted. The Site may include inaccuracies, errors and materials that violate or conflict with these Terms. If a fault occurs in our Services, please report it to us at eddie.garcia@loanblocks.ai"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Your access to the Services may be occasionally restricted to allow for repairs, maintenance or the introduction of new facilities or Services. We will restore the Services as soon as we reasonably can."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"15. Third Party Materials and Content"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You understand that the Services may display, include, or make available Content, data, information, applications or materials from third parties or provide links to certain third-party web sites, including but not limited to any User Submissions, Third Party Links or Content, (\u201cThird Party Materials\u201d)."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You acknowledge and agree that the Company is not responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of such Third Party Materials, including but not limited to any intellectual property rights therein. We expressly disclaim any responsibility for all aspects of the Third Party Materials and you further acknowledge and agree that Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, goods or services in connection with any Third Party Materials. We have no obligation to monitor Third Party Materials, and we may block or disable access to any Third Party Materials (in whole or part) through the Services at any time."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Use of any third-party trademarks or third party content on or in connection with the Services does not constitute affiliation with or endorsement of these third parties. Nothing in these Terms grants you any license to third party trademarks or content, which shall remain the property of their respective owners."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "YOUR USE OF THIRD PARTY MATERIALS IS AT YOUR OWN RISK AND IS SUBJECT TO ANY ADDITIONAL TERMS, CONDITIONS AND POLICIES APPLICABLE TO SUCH THIRD PARTY MATERIALS (SUCH AS TERMS OF SERVICE OR PRIVACY POLICIES OF THE PROVIDERS OF SUCH THIRD PARTY MATERIALS)."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "16. Warranty Disclaimers; Limitation of Liability; Financial Services Disclaimer"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "THE SERVICES ARE PROVIDED \u201cAS IS\u201d AND WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, STATUTORY OR IMPLIED, RELATING TO THE SERVICES OR ANY CONTENT ON THE SERVICES, WHETHER PROVIDED OR OWNED BY THE COMPANY OR BY ANY THIRD PARTY, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, FREEDOM FROM COMPUTER VIRUS, AND ANY IMPLIED WARRANTIES ARISING FROM COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE IN TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. IN ADDITION, YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SERVICES AND THE COMPANY DOES NOT MAKE ANY REPRESENTATION OR WARRANTY THAT ANY OF THE SERVICES OR ANY CONTENT AVAILABLE THROUGH ANY OF THE SERVICES IS ACCURATE, COMPLETE, AVAILABLE, CURRENT, FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR DEFECTS, OR THAT THE SERVICES WILL COMPLY WITH THESE TERMS, BE UNINTERRUPTED OR MEET YOUR REQUIREMENTS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM COMPANY SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. ALL DISCLAIMERS OF ANY KIND (INCLUDING IN THIS SECTION AND ELSEWHERE IN THESE TERMS) ARE MADE FOR THE BENEFIT OF THE COMPANY, ITS AFFILIATES, SUPPLIERS, LICENSORS OR SERVICE PROVIDERS INCLUDING THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, SHAREHOLDERS, AGENTS, LICENSORS, SUPPLIERS OR REPRESENTATIVES (COLLECTIVELY, THE \u201cAFFILIATED ENTITIES\u201d), AND THEIR RESPECTIVE SUCCESSORS AND ASSIGNS."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "IN NO EVENT WHATSOEVER SHALL THE COMPANY OR ITS AFFILIATED ENTITIES, BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES, OR FOR ANY USE OF DATA, LOSS OF SECURITY OF USER SUBMISSIONS (INCLUDING UNAUTHORIZED INTERCEPTION BY THIRD PARTIES OF ANY USER SUBMISSIONS), LOSS OF PROFITS OR REVENUE, INCLUDING BUT NOT LIMITED TO LOSS OF SALES, PROFIT, REVENUE, GOODWILL, OR DOWNTIME, OR LOSS OF OTHER INTANGIBLES (ARISING UNDER TORT, CONTRACT, INCLUDING BUT NOT LIMITED TO STRICT LIABILITY, OR OTHER LAW OR THEORY) REGARDLESS OF SUCH PARTY\u2019S NEGLIGENCE OR WHETHER SUCH PARTY KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. YOU UNDERSTAND AND AGREE THAT THE DOWNLOAD OF ANY MATERIALS IN CONNECTION WITH THE SERVICES IS DONE AT YOUR DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY LOSS OR DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT MAY RESULT FROM THE DOWNLOAD OR UPLOAD OF ANY MATERIAL. WITHOUT LIMITING THE FOREGOING, COMPANY WILL NOT BE LIABLE FOR DAMAGES OF ANY KIND RESULTING FROM YOUR USE OF OR INABILITY TO USE THE SERVICES OR FROM ANY CONTENT. COMPANY NEITHER ASSUMES, NOR DOES IT AUTHORIZE ANY OTHER PERSON TO ASSUME ON ITS BEHALF, ANY OTHER LIABILITY IN CONNECTION WITH THE PROVISION OF THE SERVICES. YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SITE, SERVICES, CONTENT OR THIRD PARTY MATERIALS IS TO STOP USING THE SERVICES. IF, NOTWITHSTANDING THE OTHER PROVISIONS OF THESE TERMS, COMPANY IS FOUND TO BE LIABLE TO YOU FOR ANY DAMAGE OR LOSS WHICH ARISES OUT OF OR IS IN ANY WAY CONNECTED WITH YOUR USE OF ANY SERVICES, COMPANY\u2019S LIABILITY SHALL IN NO EVENT EXCEED THE GREATER OF (1) THE TOTAL OF ANY FEES PAID BY YOU TO COMPANY IN THE SIX (6) MONTHS PRIOR TO THE DATE THE CLAIM IS ASSERTED FOR ANY OF THE SERVICES OR FEATURE RELEVANT TO THE CLAIM, OR (2) US$500.00."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "THESE DISCLAIMERS AND LIMITATIONS OF LIABILITY ARE MADE TO THE FULLEST EXTENT PERMITTED BY LAW. ALL LIMITATIONS OF LIABILITY OF ANY KIND (INCLUDING IN THIS SECTION AND ELSEWHERE IN THESE TERMS) ARE MADE FOR THE BENEFIT OF BOTH COMPANY AND THE AFFILIATED ENTITIES, AND THEIR RESPECTIVE SUCCESSORS AND ASSIGNS."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"17. Indemnification"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You agree to defend, indemnify and hold harmless the Company and its Affiliated Entities, including any successors and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees (including reasonable attorneys' fees) arising out of or relating to (1) your violation or alleged violation of these Terms; or (2) your use of the Services or your use of any information obtained through the Services (including all User Submissions)."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"18. Governing Law"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "No matter where you\u2019re located, the laws of the state of New York will govern these Terms and the relationship between you and the Company as if you signed these Terms in New York, without regard to New York state\u2019s conflicts of laws rules. If any provisions of these Terms are inconsistent with any applicable law, those provisions will be superseded and/or modified only to the extent such provisions are inconsistent."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"19. Arbitration"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "AT OUR SOLE DISCRETION, WE MAY REQUIRE YOU TO SUBMIT ANY DISPUTES ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICES, OR ANY ASPECT OF THE RELATIONSHIP BETWEEN YOU AND COMPANY, WHETHER BASED IN CONTRACT, TORT, STATUTE, FRAUD, MISREPRESENTATION OR ANY OTHER LEGAL THEORY, INCLUDING DISPUTES ARISING FROM OR CONCERNING THEIR INTERPRETATION, VIOLATION, INVALIDITY, NON-PERFORMANCE, OR TERMINATION, TO FINAL AND BINDING ARBITRATION BEFORE A NEUTRAL ARBITRATOR INSTEAD OF IN A COURT BY A JUDGE OR JURY, AND YOU AGREE THAT COMPANY AND YOU ARE EACH WAIVING THE RIGHT TO TRIAL BY A JURY."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "YOU AGREE THAT ANY ARBITRATION UNDER THESE TERMS WILL TAKE PLACE ON AN INDIVIDUAL BASIS; CLASS ARBITRATIONS AND CLASS ACTIONS ARE NOT PERMITTED AND YOU ARE AGREEING TO GIVE UP THE ABILITY TO PARTICIPATEIN A CLASS ACTION. The arbitration will be administered under the rules of American Arbitration Association under its Commercial Arbitration Rules, as amended by these Terms. The Commercial Arbitration Rules are available online at https://www.adr.org/sites/default/files/Consumer_Rules_Web_2.pdf. Any in-person appearances will be held in New York County, New York, U.S.A. The arbitrator\u2019s decision will follow these Terms and will be final and binding. The arbitrator will have authority to award temporary, interim or permanent injunctive relief or relief providing for specific performance of these Terms, but only to the extent necessary to provide relief warranted by the individual claim before the arbitrator. The award rendered by the arbitrator may be confirmed and enforced in any court having jurisdiction thereof."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {""}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"20. Miscellaneous"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"a. Severability"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "If it turns out that any part of these Terms is invalid, void, or for any reason unenforceable, that term will be deemed severable and limited or eliminated to the minimum extent necessary. The limitation or elimination of the term will not affect any other terms."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"b. Entire Agreement"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "These Terms (and, if applicable, the Master Services Agreement) constitute the entire agreement between you and the Company and supersede all prior or contemporaneous communications proposals, whether electronic, oral, or written with respect to these Services. Any rights not expressly granted herein are reserved."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"c. Headings"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Any heading, caption or section title contained herein is for convenience only, and in no way defines or explains any section or provision. All terms defined in the singular shall have the same meanings when used in the plural, where appropriate and unless otherwise specified. Any use of the term \u201cincluding\u201d or variations thereof in these Terms shall be construed as if followed by the phrase \u201cwithout limitation.\u201d"
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"d. Force Majeure"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "We will not be liable for any failure to perform any of our obligations stated in these Terms if the failure results from a cause beyond our reasonable control, including\u2014without limitation\u2014 mechanical, electronic or communications failure or degradation, strikes or other labor disputes (whether or not relating to our workforce), restraints or delays affecting carriers, or our inability or delay in obtaining supplies of adequate or suitable materials."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"e. Assignment"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You cannot assign, transfer or sublicense these Terms without first obtaining our prior written consent. We may assign, transfer, or delegate any of our rights and obligations without consent. These Terms do not create any agency, partnership, joint venture, franchisor-franchisee or employment relationship, and neither party has any authority to bind the other in any respect."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"f. Waiver"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "If we do not enforce any part of these Terms, it does not mean we give up the right to later enforce that or any other part of these Terms. In order for any waiver of compliance with these Terms to be binding, we must provide you with written notice of such waiver through one of our authorized representatives. No waiver by either party of any breach or default under these Terms will be deemed to be a waiver of any preceding or subsequent breach or default."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"g. Release"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "You release the Company and our successors from all losses, damages, rights, and demands and actions of any kind, including personal injuries, death, and property damage, that are directly or indirectly related to or arise from your use of the Services (collectively, \u201cClaims\u201d). If you are a California resident, you hereby waive California Civil Code Section 1542, which states, \u201cA general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his favor at the time of executing the release, which, if known by him would have materially affected his settlement with the debtor.\u201d This release does not apply to any Claims for unconscionable commercial practice by the Company or fraud, deception, false, promise, misrepresentation or concealment, or suppression or omission of any material fact in connection with the Services."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"h. Notices"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "Notices to you (including notices of changes to these Terms) may be made via posting to the Services or by e-mail (including in each case via links), or by regular mail. Without limitation, a printed version of these Terms and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form."
                }
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {"i. Comments, Concerns and Complaints"}
              </span>
              <React.Fragment>{"\n"}</React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#FFFFFF" }}
              >
                {
                  "All Feedback, comments, requests for technical support and other communications relating to the Services should be directed to: eddie.garcia@loanblocks.ai."
                }
              </span>
            </React.Fragment>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.column__p5Acl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cnt3T
                )}
              >
                {"\u00a9 2024 LOANBLOCKS Inc. All rights reserved."}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__v3ILx)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__vNtBh
                )}
                href={`/terms`}
                platform={"react"}
              >
                {"Terms of Service"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.column__q4HUd)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link___7Wcdh
                )}
                href={`/privacy-policy`}
                platform={"react"}
              >
                {"Privacy Policy"}
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.column__p7Ezf)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__wxaE4)}
                displayHeight={"32px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"189.935px"}
                loading={"lazy"}
                src={{
                  src: lbLogoVfSlJptRmlfu,
                  fullWidth: 305,
                  fullHeight: 50,
                  aspectRatio: 6.1
                }}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "heroMessage", "terms", "footer"],
  heroMessage: ["heroMessage"],
  terms: ["terms"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroMessage: "div";
  terms: "div";
  footer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTermsOfService__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTermsOfService__VariantsArgs;
    args?: PlasmicTermsOfService__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTermsOfService__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTermsOfService__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTermsOfService__ArgProps,
          internalVariantPropNames: PlasmicTermsOfService__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTermsOfService__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTermsOfService";
  } else {
    func.displayName = `PlasmicTermsOfService.${nodeName}`;
  }
  return func;
}

export const PlasmicTermsOfService = Object.assign(
  // Top-level PlasmicTermsOfService renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroMessage: makeNodeComponent("heroMessage"),
    terms: makeNodeComponent("terms"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicTermsOfService
    internalVariantProps: PlasmicTermsOfService__VariantProps,
    internalArgProps: PlasmicTermsOfService__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Loanblocks | Terms of Service",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTermsOfService;
/* prettier-ignore-end */
